name: CI

on: [push]

env:
  IMAGE_NAME: actions-example
  IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 300

    steps:
      - uses: actions/checkout@v1

      - name: Build Docker Image
        run: cd docker/ && make build && cd ../

      - name: Add Tag
        run: docker tag ${IMAGE_NAME} docker.pkg.github.com/${{ github.repository }}/${IMAGE_NAME}:${IMAGE_TAG}

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Login GitHub Registry
        # 自動生成されるGITHUB_TOKENを使用する
        run: docker login docker.pkg.github.com -u owner -p ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to GitHub Registry
        run: docker push docker.pkg.github.com/${{ github.repository }}/${IMAGE_NAME}:${IMAGE_TAG}
