name: CI

on: [push]

env:
  IMAGE_NAME: actions-example
  IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 300

    steps:
      - uses: actions/checkout@v1
      - name: Build Docker Image
        run: cd docker/ && make build && cd ../
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Login GitHub Registry
        run: |
          docker login docker.pkg.github.com -u owner -p ${{ secrets.GITHUB_TOKEN }}
          echo IMAGE_NAME= ${IMAGE_NAME}
          echo IMAGE_TAG= ${IMAGE_TAG}
